// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: ../../components/api-server/openapi/openapi.yaml
// Spec SHA256: 4f16ee432c4370397b65ba2fc0f1a28d5b813c0ae26c388667d5684a8b825020
// Generated: 1970-01-01T00:00:00Z

import type { ObjectReference, ListMeta } from './base.js';

export type Fleet = ObjectReference & {
  description: string;
  name: string;
  status: string;
};

export type FleetList = ListMeta & {
  items: Fleet[];
};

export type FleetCreateRequest = {
  description?: string;
  name: string;
  status?: string;
};

export type FleetPatchRequest = {
  description?: string;
  name?: string;
  status?: string;
};

export class FleetBuilder {
  private data: Record<string, unknown> = {};


  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): FleetCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as FleetCreateRequest;
  }
}

export class FleetPatchBuilder {
  private data: Record<string, unknown> = {};


  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): FleetPatchRequest {
    return this.data as FleetPatchRequest;
  }
}

