apiVersion: v1
kind: Namespace
metadata:
  name: NAMESPACE_PLACEHOLDER
  labels:
    app.kubernetes.io/name: hypershell
    app.kubernetes.io/part-of: hypershell
    hypershell.redhat.io/local-development: "true"
