// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hypershell/v1/fleets.proto

package hypershell_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Fleet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fleet) Reset() {
	*x = Fleet{}
	mi := &file_hypershell_v1_fleets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fleet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fleet) ProtoMessage() {}

func (x *Fleet) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_fleets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fleet.ProtoReflect.Descriptor instead.
func (*Fleet) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_fleets_proto_rawDescGZIP(), []int{0}
}

func (x *Fleet) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Fleet) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Fleet) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Fleet) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type CreateFleetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFleetRequest) Reset() {
	*x = CreateFleetRequest{}
	mi := &file_hypershell_v1_fleets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFleetRequest) ProtoMessage() {}

func (x *CreateFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_fleets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFleetRequest.ProtoReflect.Descriptor instead.
func (*CreateFleetRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_fleets_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFleetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFleetRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateFleetRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type GetFleetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFleetRequest) Reset() {
	*x = GetFleetRequest{}
	mi := &file_hypershell_v1_fleets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFleetRequest) ProtoMessage() {}

func (x *GetFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_fleets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFleetRequest.ProtoReflect.Descriptor instead.
func (*GetFleetRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_fleets_proto_rawDescGZIP(), []int{2}
}

func (x *GetFleetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateFleetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        *string                `protobuf:"bytes,4,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFleetRequest) Reset() {
	*x = UpdateFleetRequest{}
	mi := &file_hypershell_v1_fleets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFleetRequest) ProtoMessage() {}

func (x *UpdateFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_fleets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFleetRequest.ProtoReflect.Descriptor instead.
func (*UpdateFleetRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_fleets_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFleetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFleetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateFleetRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateFleetRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type DeleteFleetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFleetRequest) Reset() {
	*x = DeleteFleetRequest{}
	mi := &file_hypershell_v1_fleets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFleetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFleetRequest) ProtoMessage() {}

func (x *DeleteFleetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_fleets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFleetRequest.ProtoReflect.Descriptor instead.
func (*DeleteFleetRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_fleets_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFleetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListFleetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFleetsRequest) Reset() {
	*x = ListFleetsRequest{}
	mi := &file_hypershell_v1_fleets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFleetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFleetsRequest) ProtoMessage() {}

func (x *ListFleetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_fleets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFleetsRequest.ProtoReflect.Descriptor instead.
func (*ListFleetsRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_fleets_proto_rawDescGZIP(), []int{5}
}

func (x *ListFleetsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFleetsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFleetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Fleet               `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFleetsResponse) Reset() {
	*x = ListFleetsResponse{}
	mi := &file_hypershell_v1_fleets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFleetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFleetsResponse) ProtoMessage() {}

func (x *ListFleetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_fleets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFleetsResponse.ProtoReflect.Descriptor instead.
func (*ListFleetsResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_fleets_proto_rawDescGZIP(), []int{6}
}

func (x *ListFleetsResponse) GetItems() []*Fleet {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListFleetsResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteFleetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFleetResponse) Reset() {
	*x = DeleteFleetResponse{}
	mi := &file_hypershell_v1_fleets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFleetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFleetResponse) ProtoMessage() {}

func (x *DeleteFleetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_fleets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFleetResponse.ProtoReflect.Descriptor instead.
func (*DeleteFleetResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_fleets_proto_rawDescGZIP(), []int{7}
}

type WatchFleetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchFleetsRequest) Reset() {
	*x = WatchFleetsRequest{}
	mi := &file_hypershell_v1_fleets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchFleetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchFleetsRequest) ProtoMessage() {}

func (x *WatchFleetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_fleets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchFleetsRequest.ProtoReflect.Descriptor instead.
func (*WatchFleetsRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_fleets_proto_rawDescGZIP(), []int{8}
}

type FleetWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=hypershell.v1.EventType" json:"type,omitempty"`
	Fleet         *Fleet                 `protobuf:"bytes,2,opt,name=fleet,proto3" json:"fleet,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FleetWatchEvent) Reset() {
	*x = FleetWatchEvent{}
	mi := &file_hypershell_v1_fleets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FleetWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FleetWatchEvent) ProtoMessage() {}

func (x *FleetWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_fleets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FleetWatchEvent.ProtoReflect.Descriptor instead.
func (*FleetWatchEvent) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_fleets_proto_rawDescGZIP(), []int{9}
}

func (x *FleetWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *FleetWatchEvent) GetFleet() *Fleet {
	if x != nil {
		return x.Fleet
	}
	return nil
}

func (x *FleetWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_hypershell_v1_fleets_proto protoreflect.FileDescriptor

const file_hypershell_v1_fleets_proto_rawDesc = "" +
	"\n" +
	"\x1ahypershell/v1/fleets.proto\x12\rhypershell.v1\x1a\x1ahypershell/v1/common.proto\"\xb6\x01\n" +
	"\x05Fleet\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.hypershell.v1.ObjectReferenceR\bmetadata\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x01R\x06status\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_status\"\x87\x01\n" +
	"\x12CreateFleetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x01R\x06status\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_status\"!\n" +
	"\x0fGetFleetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa5\x01\n" +
	"\x12UpdateFleetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x04 \x01(\tH\x02R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_status\"$\n" +
	"\x12DeleteFleetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\";\n" +
	"\x11ListFleetsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"u\n" +
	"\x12ListFleetsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.hypershell.v1.FleetR\x05items\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.hypershell.v1.ListMetaR\bmetadata\"\x15\n" +
	"\x13DeleteFleetResponse\"\x14\n" +
	"\x12WatchFleetsRequest\"\x8c\x01\n" +
	"\x0fFleetWatchEvent\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.hypershell.v1.EventTypeR\x04type\x12*\n" +
	"\x05fleet\x18\x02 \x01(\v2\x14.hypershell.v1.FleetR\x05fleet\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\xdd\x03\n" +
	"\fFleetService\x12@\n" +
	"\bGetFleet\x12\x1e.hypershell.v1.GetFleetRequest\x1a\x14.hypershell.v1.Fleet\x12F\n" +
	"\vCreateFleet\x12!.hypershell.v1.CreateFleetRequest\x1a\x14.hypershell.v1.Fleet\x12F\n" +
	"\vUpdateFleet\x12!.hypershell.v1.UpdateFleetRequest\x1a\x14.hypershell.v1.Fleet\x12T\n" +
	"\vDeleteFleet\x12!.hypershell.v1.DeleteFleetRequest\x1a\".hypershell.v1.DeleteFleetResponse\x12Q\n" +
	"\n" +
	"ListFleets\x12 .hypershell.v1.ListFleetsRequest\x1a!.hypershell.v1.ListFleetsResponse\x12R\n" +
	"\vWatchFleets\x12!.hypershell.v1.WatchFleetsRequest\x1a\x1e.hypershell.v1.FleetWatchEvent0\x01BgZegithub.com/openshift-online/hypershell/components/api-server/pkg/api/grpc/hypershell/v1;hypershell_v1b\x06proto3"

var (
	file_hypershell_v1_fleets_proto_rawDescOnce sync.Once
	file_hypershell_v1_fleets_proto_rawDescData []byte
)

func file_hypershell_v1_fleets_proto_rawDescGZIP() []byte {
	file_hypershell_v1_fleets_proto_rawDescOnce.Do(func() {
		file_hypershell_v1_fleets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hypershell_v1_fleets_proto_rawDesc), len(file_hypershell_v1_fleets_proto_rawDesc)))
	})
	return file_hypershell_v1_fleets_proto_rawDescData
}

var file_hypershell_v1_fleets_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hypershell_v1_fleets_proto_goTypes = []any{
	(*Fleet)(nil),               // 0: hypershell.v1.Fleet
	(*CreateFleetRequest)(nil),  // 1: hypershell.v1.CreateFleetRequest
	(*GetFleetRequest)(nil),     // 2: hypershell.v1.GetFleetRequest
	(*UpdateFleetRequest)(nil),  // 3: hypershell.v1.UpdateFleetRequest
	(*DeleteFleetRequest)(nil),  // 4: hypershell.v1.DeleteFleetRequest
	(*ListFleetsRequest)(nil),   // 5: hypershell.v1.ListFleetsRequest
	(*ListFleetsResponse)(nil),  // 6: hypershell.v1.ListFleetsResponse
	(*DeleteFleetResponse)(nil), // 7: hypershell.v1.DeleteFleetResponse
	(*WatchFleetsRequest)(nil),  // 8: hypershell.v1.WatchFleetsRequest
	(*FleetWatchEvent)(nil),     // 9: hypershell.v1.FleetWatchEvent
	(*ObjectReference)(nil),     // 10: hypershell.v1.ObjectReference
	(*ListMeta)(nil),            // 11: hypershell.v1.ListMeta
	(EventType)(0),              // 12: hypershell.v1.EventType
}
var file_hypershell_v1_fleets_proto_depIdxs = []int32{
	10, // 0: hypershell.v1.Fleet.metadata:type_name -> hypershell.v1.ObjectReference
	0,  // 1: hypershell.v1.ListFleetsResponse.items:type_name -> hypershell.v1.Fleet
	11, // 2: hypershell.v1.ListFleetsResponse.metadata:type_name -> hypershell.v1.ListMeta
	12, // 3: hypershell.v1.FleetWatchEvent.type:type_name -> hypershell.v1.EventType
	0,  // 4: hypershell.v1.FleetWatchEvent.fleet:type_name -> hypershell.v1.Fleet
	2,  // 5: hypershell.v1.FleetService.GetFleet:input_type -> hypershell.v1.GetFleetRequest
	1,  // 6: hypershell.v1.FleetService.CreateFleet:input_type -> hypershell.v1.CreateFleetRequest
	3,  // 7: hypershell.v1.FleetService.UpdateFleet:input_type -> hypershell.v1.UpdateFleetRequest
	4,  // 8: hypershell.v1.FleetService.DeleteFleet:input_type -> hypershell.v1.DeleteFleetRequest
	5,  // 9: hypershell.v1.FleetService.ListFleets:input_type -> hypershell.v1.ListFleetsRequest
	8,  // 10: hypershell.v1.FleetService.WatchFleets:input_type -> hypershell.v1.WatchFleetsRequest
	0,  // 11: hypershell.v1.FleetService.GetFleet:output_type -> hypershell.v1.Fleet
	0,  // 12: hypershell.v1.FleetService.CreateFleet:output_type -> hypershell.v1.Fleet
	0,  // 13: hypershell.v1.FleetService.UpdateFleet:output_type -> hypershell.v1.Fleet
	7,  // 14: hypershell.v1.FleetService.DeleteFleet:output_type -> hypershell.v1.DeleteFleetResponse
	6,  // 15: hypershell.v1.FleetService.ListFleets:output_type -> hypershell.v1.ListFleetsResponse
	9,  // 16: hypershell.v1.FleetService.WatchFleets:output_type -> hypershell.v1.FleetWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_hypershell_v1_fleets_proto_init() }
func file_hypershell_v1_fleets_proto_init() {
	if File_hypershell_v1_fleets_proto != nil {
		return
	}
	file_hypershell_v1_common_proto_init()
	file_hypershell_v1_fleets_proto_msgTypes[0].OneofWrappers = []any{}
	file_hypershell_v1_fleets_proto_msgTypes[1].OneofWrappers = []any{}
	file_hypershell_v1_fleets_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hypershell_v1_fleets_proto_rawDesc), len(file_hypershell_v1_fleets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hypershell_v1_fleets_proto_goTypes,
		DependencyIndexes: file_hypershell_v1_fleets_proto_depIdxs,
		MessageInfos:      file_hypershell_v1_fleets_proto_msgTypes,
	}.Build()
	File_hypershell_v1_fleets_proto = out.File
	file_hypershell_v1_fleets_proto_goTypes = nil
	file_hypershell_v1_fleets_proto_depIdxs = nil
}
