// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hypershell/v1/gateway_networks.proto

package hypershell_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayNetwork struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	FleetId       string                 `protobuf:"bytes,3,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`
	Topology      *string                `protobuf:"bytes,4,opt,name=topology,proto3,oneof" json:"topology,omitempty"`
	TunnelMode    *string                `protobuf:"bytes,5,opt,name=tunnel_mode,json=tunnelMode,proto3,oneof" json:"tunnel_mode,omitempty"`
	HubGatewayId  *string                `protobuf:"bytes,6,opt,name=hub_gateway_id,json=hubGatewayId,proto3,oneof" json:"hub_gateway_id,omitempty"`
	Status        *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayNetwork) Reset() {
	*x = GatewayNetwork{}
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayNetwork) ProtoMessage() {}

func (x *GatewayNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayNetwork.ProtoReflect.Descriptor instead.
func (*GatewayNetwork) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_gateway_networks_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayNetwork) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *GatewayNetwork) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GatewayNetwork) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *GatewayNetwork) GetTopology() string {
	if x != nil && x.Topology != nil {
		return *x.Topology
	}
	return ""
}

func (x *GatewayNetwork) GetTunnelMode() string {
	if x != nil && x.TunnelMode != nil {
		return *x.TunnelMode
	}
	return ""
}

func (x *GatewayNetwork) GetHubGatewayId() string {
	if x != nil && x.HubGatewayId != nil {
		return *x.HubGatewayId
	}
	return ""
}

func (x *GatewayNetwork) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type CreateGatewayNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FleetId       string                 `protobuf:"bytes,2,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`
	Topology      *string                `protobuf:"bytes,3,opt,name=topology,proto3,oneof" json:"topology,omitempty"`
	TunnelMode    *string                `protobuf:"bytes,4,opt,name=tunnel_mode,json=tunnelMode,proto3,oneof" json:"tunnel_mode,omitempty"`
	HubGatewayId  *string                `protobuf:"bytes,5,opt,name=hub_gateway_id,json=hubGatewayId,proto3,oneof" json:"hub_gateway_id,omitempty"`
	Status        *string                `protobuf:"bytes,6,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGatewayNetworkRequest) Reset() {
	*x = CreateGatewayNetworkRequest{}
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGatewayNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGatewayNetworkRequest) ProtoMessage() {}

func (x *CreateGatewayNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGatewayNetworkRequest.ProtoReflect.Descriptor instead.
func (*CreateGatewayNetworkRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_gateway_networks_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGatewayNetworkRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGatewayNetworkRequest) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *CreateGatewayNetworkRequest) GetTopology() string {
	if x != nil && x.Topology != nil {
		return *x.Topology
	}
	return ""
}

func (x *CreateGatewayNetworkRequest) GetTunnelMode() string {
	if x != nil && x.TunnelMode != nil {
		return *x.TunnelMode
	}
	return ""
}

func (x *CreateGatewayNetworkRequest) GetHubGatewayId() string {
	if x != nil && x.HubGatewayId != nil {
		return *x.HubGatewayId
	}
	return ""
}

func (x *CreateGatewayNetworkRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type GetGatewayNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGatewayNetworkRequest) Reset() {
	*x = GetGatewayNetworkRequest{}
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGatewayNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGatewayNetworkRequest) ProtoMessage() {}

func (x *GetGatewayNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGatewayNetworkRequest.ProtoReflect.Descriptor instead.
func (*GetGatewayNetworkRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_gateway_networks_proto_rawDescGZIP(), []int{2}
}

func (x *GetGatewayNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateGatewayNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	FleetId       *string                `protobuf:"bytes,3,opt,name=fleet_id,json=fleetId,proto3,oneof" json:"fleet_id,omitempty"`
	Topology      *string                `protobuf:"bytes,4,opt,name=topology,proto3,oneof" json:"topology,omitempty"`
	TunnelMode    *string                `protobuf:"bytes,5,opt,name=tunnel_mode,json=tunnelMode,proto3,oneof" json:"tunnel_mode,omitempty"`
	HubGatewayId  *string                `protobuf:"bytes,6,opt,name=hub_gateway_id,json=hubGatewayId,proto3,oneof" json:"hub_gateway_id,omitempty"`
	Status        *string                `protobuf:"bytes,7,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGatewayNetworkRequest) Reset() {
	*x = UpdateGatewayNetworkRequest{}
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGatewayNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGatewayNetworkRequest) ProtoMessage() {}

func (x *UpdateGatewayNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGatewayNetworkRequest.ProtoReflect.Descriptor instead.
func (*UpdateGatewayNetworkRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_gateway_networks_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateGatewayNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateGatewayNetworkRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateGatewayNetworkRequest) GetFleetId() string {
	if x != nil && x.FleetId != nil {
		return *x.FleetId
	}
	return ""
}

func (x *UpdateGatewayNetworkRequest) GetTopology() string {
	if x != nil && x.Topology != nil {
		return *x.Topology
	}
	return ""
}

func (x *UpdateGatewayNetworkRequest) GetTunnelMode() string {
	if x != nil && x.TunnelMode != nil {
		return *x.TunnelMode
	}
	return ""
}

func (x *UpdateGatewayNetworkRequest) GetHubGatewayId() string {
	if x != nil && x.HubGatewayId != nil {
		return *x.HubGatewayId
	}
	return ""
}

func (x *UpdateGatewayNetworkRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type DeleteGatewayNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGatewayNetworkRequest) Reset() {
	*x = DeleteGatewayNetworkRequest{}
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGatewayNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGatewayNetworkRequest) ProtoMessage() {}

func (x *DeleteGatewayNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGatewayNetworkRequest.ProtoReflect.Descriptor instead.
func (*DeleteGatewayNetworkRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_gateway_networks_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteGatewayNetworkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListGatewayNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewayNetworksRequest) Reset() {
	*x = ListGatewayNetworksRequest{}
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewayNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewayNetworksRequest) ProtoMessage() {}

func (x *ListGatewayNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewayNetworksRequest.ProtoReflect.Descriptor instead.
func (*ListGatewayNetworksRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_gateway_networks_proto_rawDescGZIP(), []int{5}
}

func (x *ListGatewayNetworksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListGatewayNetworksRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListGatewayNetworksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GatewayNetwork      `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGatewayNetworksResponse) Reset() {
	*x = ListGatewayNetworksResponse{}
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGatewayNetworksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGatewayNetworksResponse) ProtoMessage() {}

func (x *ListGatewayNetworksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGatewayNetworksResponse.ProtoReflect.Descriptor instead.
func (*ListGatewayNetworksResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_gateway_networks_proto_rawDescGZIP(), []int{6}
}

func (x *ListGatewayNetworksResponse) GetItems() []*GatewayNetwork {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListGatewayNetworksResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteGatewayNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGatewayNetworkResponse) Reset() {
	*x = DeleteGatewayNetworkResponse{}
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGatewayNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGatewayNetworkResponse) ProtoMessage() {}

func (x *DeleteGatewayNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGatewayNetworkResponse.ProtoReflect.Descriptor instead.
func (*DeleteGatewayNetworkResponse) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_gateway_networks_proto_rawDescGZIP(), []int{7}
}

type WatchGatewayNetworksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchGatewayNetworksRequest) Reset() {
	*x = WatchGatewayNetworksRequest{}
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchGatewayNetworksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchGatewayNetworksRequest) ProtoMessage() {}

func (x *WatchGatewayNetworksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchGatewayNetworksRequest.ProtoReflect.Descriptor instead.
func (*WatchGatewayNetworksRequest) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_gateway_networks_proto_rawDescGZIP(), []int{8}
}

type GatewayNetworkWatchEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=hypershell.v1.EventType" json:"type,omitempty"`
	GatewayNetwork *GatewayNetwork        `protobuf:"bytes,2,opt,name=gatewayNetwork,proto3" json:"gatewayNetwork,omitempty"`
	ResourceId     string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GatewayNetworkWatchEvent) Reset() {
	*x = GatewayNetworkWatchEvent{}
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayNetworkWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayNetworkWatchEvent) ProtoMessage() {}

func (x *GatewayNetworkWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_hypershell_v1_gateway_networks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayNetworkWatchEvent.ProtoReflect.Descriptor instead.
func (*GatewayNetworkWatchEvent) Descriptor() ([]byte, []int) {
	return file_hypershell_v1_gateway_networks_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayNetworkWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *GatewayNetworkWatchEvent) GetGatewayNetwork() *GatewayNetwork {
	if x != nil {
		return x.GatewayNetwork
	}
	return nil
}

func (x *GatewayNetworkWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_hypershell_v1_gateway_networks_proto protoreflect.FileDescriptor

const file_hypershell_v1_gateway_networks_proto_rawDesc = "" +
	"\n" +
	"$hypershell/v1/gateway_networks.proto\x12\rhypershell.v1\x1a\x1ahypershell/v1/common.proto\"\xc5\x02\n" +
	"\x0eGatewayNetwork\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.hypershell.v1.ObjectReferenceR\bmetadata\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bfleet_id\x18\x03 \x01(\tR\afleetId\x12\x1f\n" +
	"\btopology\x18\x04 \x01(\tH\x00R\btopology\x88\x01\x01\x12$\n" +
	"\vtunnel_mode\x18\x05 \x01(\tH\x01R\n" +
	"tunnelMode\x88\x01\x01\x12)\n" +
	"\x0ehub_gateway_id\x18\x06 \x01(\tH\x02R\fhubGatewayId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x03R\x06status\x88\x01\x01B\v\n" +
	"\t_topologyB\x0e\n" +
	"\f_tunnel_modeB\x11\n" +
	"\x0f_hub_gateway_idB\t\n" +
	"\a_status\"\x96\x02\n" +
	"\x1bCreateGatewayNetworkRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bfleet_id\x18\x02 \x01(\tR\afleetId\x12\x1f\n" +
	"\btopology\x18\x03 \x01(\tH\x00R\btopology\x88\x01\x01\x12$\n" +
	"\vtunnel_mode\x18\x04 \x01(\tH\x01R\n" +
	"tunnelMode\x88\x01\x01\x12)\n" +
	"\x0ehub_gateway_id\x18\x05 \x01(\tH\x02R\fhubGatewayId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x06 \x01(\tH\x03R\x06status\x88\x01\x01B\v\n" +
	"\t_topologyB\x0e\n" +
	"\f_tunnel_modeB\x11\n" +
	"\x0f_hub_gateway_idB\t\n" +
	"\a_status\"*\n" +
	"\x18GetGatewayNetworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc6\x02\n" +
	"\x1bUpdateGatewayNetworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1e\n" +
	"\bfleet_id\x18\x03 \x01(\tH\x01R\afleetId\x88\x01\x01\x12\x1f\n" +
	"\btopology\x18\x04 \x01(\tH\x02R\btopology\x88\x01\x01\x12$\n" +
	"\vtunnel_mode\x18\x05 \x01(\tH\x03R\n" +
	"tunnelMode\x88\x01\x01\x12)\n" +
	"\x0ehub_gateway_id\x18\x06 \x01(\tH\x04R\fhubGatewayId\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\a \x01(\tH\x05R\x06status\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_fleet_idB\v\n" +
	"\t_topologyB\x0e\n" +
	"\f_tunnel_modeB\x11\n" +
	"\x0f_hub_gateway_idB\t\n" +
	"\a_status\"-\n" +
	"\x1bDeleteGatewayNetworkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"D\n" +
	"\x1aListGatewayNetworksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x87\x01\n" +
	"\x1bListGatewayNetworksResponse\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.hypershell.v1.GatewayNetworkR\x05items\x123\n" +
	"\bmetadata\x18\x02 \x01(\v2\x17.hypershell.v1.ListMetaR\bmetadata\"\x1e\n" +
	"\x1cDeleteGatewayNetworkResponse\"\x1d\n" +
	"\x1bWatchGatewayNetworksRequest\"\xb0\x01\n" +
	"\x18GatewayNetworkWatchEvent\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.hypershell.v1.EventTypeR\x04type\x12E\n" +
	"\x0egatewayNetwork\x18\x02 \x01(\v2\x1d.hypershell.v1.GatewayNetworkR\x0egatewayNetwork\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId2\x88\x05\n" +
	"\x15GatewayNetworkService\x12[\n" +
	"\x11GetGatewayNetwork\x12'.hypershell.v1.GetGatewayNetworkRequest\x1a\x1d.hypershell.v1.GatewayNetwork\x12a\n" +
	"\x14CreateGatewayNetwork\x12*.hypershell.v1.CreateGatewayNetworkRequest\x1a\x1d.hypershell.v1.GatewayNetwork\x12a\n" +
	"\x14UpdateGatewayNetwork\x12*.hypershell.v1.UpdateGatewayNetworkRequest\x1a\x1d.hypershell.v1.GatewayNetwork\x12o\n" +
	"\x14DeleteGatewayNetwork\x12*.hypershell.v1.DeleteGatewayNetworkRequest\x1a+.hypershell.v1.DeleteGatewayNetworkResponse\x12l\n" +
	"\x13ListGatewayNetworks\x12).hypershell.v1.ListGatewayNetworksRequest\x1a*.hypershell.v1.ListGatewayNetworksResponse\x12m\n" +
	"\x14WatchGatewayNetworks\x12*.hypershell.v1.WatchGatewayNetworksRequest\x1a'.hypershell.v1.GatewayNetworkWatchEvent0\x01BgZegithub.com/openshift-online/hypershell/components/api-server/pkg/api/grpc/hypershell/v1;hypershell_v1b\x06proto3"

var (
	file_hypershell_v1_gateway_networks_proto_rawDescOnce sync.Once
	file_hypershell_v1_gateway_networks_proto_rawDescData []byte
)

func file_hypershell_v1_gateway_networks_proto_rawDescGZIP() []byte {
	file_hypershell_v1_gateway_networks_proto_rawDescOnce.Do(func() {
		file_hypershell_v1_gateway_networks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hypershell_v1_gateway_networks_proto_rawDesc), len(file_hypershell_v1_gateway_networks_proto_rawDesc)))
	})
	return file_hypershell_v1_gateway_networks_proto_rawDescData
}

var file_hypershell_v1_gateway_networks_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_hypershell_v1_gateway_networks_proto_goTypes = []any{
	(*GatewayNetwork)(nil),               // 0: hypershell.v1.GatewayNetwork
	(*CreateGatewayNetworkRequest)(nil),  // 1: hypershell.v1.CreateGatewayNetworkRequest
	(*GetGatewayNetworkRequest)(nil),     // 2: hypershell.v1.GetGatewayNetworkRequest
	(*UpdateGatewayNetworkRequest)(nil),  // 3: hypershell.v1.UpdateGatewayNetworkRequest
	(*DeleteGatewayNetworkRequest)(nil),  // 4: hypershell.v1.DeleteGatewayNetworkRequest
	(*ListGatewayNetworksRequest)(nil),   // 5: hypershell.v1.ListGatewayNetworksRequest
	(*ListGatewayNetworksResponse)(nil),  // 6: hypershell.v1.ListGatewayNetworksResponse
	(*DeleteGatewayNetworkResponse)(nil), // 7: hypershell.v1.DeleteGatewayNetworkResponse
	(*WatchGatewayNetworksRequest)(nil),  // 8: hypershell.v1.WatchGatewayNetworksRequest
	(*GatewayNetworkWatchEvent)(nil),     // 9: hypershell.v1.GatewayNetworkWatchEvent
	(*ObjectReference)(nil),              // 10: hypershell.v1.ObjectReference
	(*ListMeta)(nil),                     // 11: hypershell.v1.ListMeta
	(EventType)(0),                       // 12: hypershell.v1.EventType
}
var file_hypershell_v1_gateway_networks_proto_depIdxs = []int32{
	10, // 0: hypershell.v1.GatewayNetwork.metadata:type_name -> hypershell.v1.ObjectReference
	0,  // 1: hypershell.v1.ListGatewayNetworksResponse.items:type_name -> hypershell.v1.GatewayNetwork
	11, // 2: hypershell.v1.ListGatewayNetworksResponse.metadata:type_name -> hypershell.v1.ListMeta
	12, // 3: hypershell.v1.GatewayNetworkWatchEvent.type:type_name -> hypershell.v1.EventType
	0,  // 4: hypershell.v1.GatewayNetworkWatchEvent.gatewayNetwork:type_name -> hypershell.v1.GatewayNetwork
	2,  // 5: hypershell.v1.GatewayNetworkService.GetGatewayNetwork:input_type -> hypershell.v1.GetGatewayNetworkRequest
	1,  // 6: hypershell.v1.GatewayNetworkService.CreateGatewayNetwork:input_type -> hypershell.v1.CreateGatewayNetworkRequest
	3,  // 7: hypershell.v1.GatewayNetworkService.UpdateGatewayNetwork:input_type -> hypershell.v1.UpdateGatewayNetworkRequest
	4,  // 8: hypershell.v1.GatewayNetworkService.DeleteGatewayNetwork:input_type -> hypershell.v1.DeleteGatewayNetworkRequest
	5,  // 9: hypershell.v1.GatewayNetworkService.ListGatewayNetworks:input_type -> hypershell.v1.ListGatewayNetworksRequest
	8,  // 10: hypershell.v1.GatewayNetworkService.WatchGatewayNetworks:input_type -> hypershell.v1.WatchGatewayNetworksRequest
	0,  // 11: hypershell.v1.GatewayNetworkService.GetGatewayNetwork:output_type -> hypershell.v1.GatewayNetwork
	0,  // 12: hypershell.v1.GatewayNetworkService.CreateGatewayNetwork:output_type -> hypershell.v1.GatewayNetwork
	0,  // 13: hypershell.v1.GatewayNetworkService.UpdateGatewayNetwork:output_type -> hypershell.v1.GatewayNetwork
	7,  // 14: hypershell.v1.GatewayNetworkService.DeleteGatewayNetwork:output_type -> hypershell.v1.DeleteGatewayNetworkResponse
	6,  // 15: hypershell.v1.GatewayNetworkService.ListGatewayNetworks:output_type -> hypershell.v1.ListGatewayNetworksResponse
	9,  // 16: hypershell.v1.GatewayNetworkService.WatchGatewayNetworks:output_type -> hypershell.v1.GatewayNetworkWatchEvent
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_hypershell_v1_gateway_networks_proto_init() }
func file_hypershell_v1_gateway_networks_proto_init() {
	if File_hypershell_v1_gateway_networks_proto != nil {
		return
	}
	file_hypershell_v1_common_proto_init()
	file_hypershell_v1_gateway_networks_proto_msgTypes[0].OneofWrappers = []any{}
	file_hypershell_v1_gateway_networks_proto_msgTypes[1].OneofWrappers = []any{}
	file_hypershell_v1_gateway_networks_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hypershell_v1_gateway_networks_proto_rawDesc), len(file_hypershell_v1_gateway_networks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hypershell_v1_gateway_networks_proto_goTypes,
		DependencyIndexes: file_hypershell_v1_gateway_networks_proto_depIdxs,
		MessageInfos:      file_hypershell_v1_gateway_networks_proto_msgTypes,
	}.Build()
	File_hypershell_v1_gateway_networks_proto = out.File
	file_hypershell_v1_gateway_networks_proto_goTypes = nil
	file_hypershell_v1_gateway_networks_proto_depIdxs = nil
}
