// Code generated by trex-sdk-generator from openapi.yaml - DO NOT EDIT.
// Source: ../../components/api-server/openapi/openapi.yaml
// Spec SHA256: 4f16ee432c4370397b65ba2fc0f1a28d5b813c0ae26c388667d5684a8b825020
// Generated: 1970-01-01T00:00:00Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/openshift-online/hypershell/components/sdk-go/types"
)

type RoleAPI struct {
	client *Client
}

func (c *Client) Roles() *RoleAPI {
	return &RoleAPI{client: c}
}

func (a *RoleAPI) Create(ctx context.Context, resource *types.Role) (*types.Role, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal role: %w", err)
	}
	var result types.Role
	if err := a.client.do(ctx, http.MethodPost, "/roles", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RoleAPI) Get(ctx context.Context, id string) (*types.Role, error) {
	var result types.Role
	if err := a.client.do(ctx, http.MethodGet, "/roles/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RoleAPI) List(ctx context.Context, opts *types.ListOptions) (*types.RoleList, error) {
	var result types.RoleList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/roles", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RoleAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Role] {
	return NewIterator(func(page int) (*types.RoleList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
