apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgres.yaml
  - api-server.yaml
  - controller.yaml
  - route.yaml
  - keycloak.yaml

configMapGenerator:
- name: keycloak-realm-config
  namespace: hypershell
  files:
  - hypershell-realm.json=../keycloak/hypershell-realm.json
  options:
    disableNameSuffixHash: true
